### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by vorons** [Extravi/tailsx#22]
Hello!
Do you have instructions on how to install this search engine?

**Comment by Extravi** [comment]
https://github.com/Extravi/tailsx-docs

I just finished documentation

**Comment by vorons** [comment]
> https://github.com/Extravi/tailsx-docs
> 
> I just finished documentation

Oh, thank you so much!

**Comment by Extravi** [comment]
np

**Comment by Extravi** [comment]
i made an update to it because i forgot to add automatically renewal for the Let’s Encrypt certificate:
https://github.com/Extravi/tailsx-docs
![image](https://github.com/Extravi/tailsx/assets/98912029/ebe7c18b-0e0a-44fd-9e70-b03f5685ad92)

**Comment by Extravi** [comment]
did you get it working?

**Comment by vorons** [comment]
> did you get it working?

Yes, thanks, it works now: https://search.svoron.com
There was one module missing, "request", I installed it with the command:
```
pip install request
```
Only the video search doesn't work:

![vedeo_search](https://github.com/Extravi/tailsx/assets/3390639/a2027281-9f31-49cb-b2c3-9529fcf89f86)

**Comment by Extravi** [comment]
the video will be fixed soon it doesn't work atm because brave search removed there video search

**Comment by Extravi** [comment]
The video will be fixed soon; it doesn't work at the moment because brave search removed their video search.

**Comment by Extravi** [comment]
Would you like me to add your instance to the instance list? and what is your instance location?

**Comment by vorons** [comment]
> Would you like me to add your instance to the instance list? and what is your instance location?

No, I think it's not worth adding to the list of instances. I use free hosting which has a limited number of requests per month. This is for personal use only.

Thanks again for a great project!

**Comment by Extravi** [comment]
np if you have any feedback let me know :+1:

**Comment by Extravi** [comment]
> > did you get it working?
> 
> Yes, thanks, it works now: https://search.svoron.com There was one module missing, "request", I installed it with the command:
> 
> ```
> pip install request
> ```
> 
> Only the video search doesn't work:
> 
> ![vedeo_search](https://user-images.githubusercontent.com/3390639/242139327-a2027281-9f31-49cb-b2c3-9529fcf89f86.png)

i have fixed the video search

**Comment by vorons** [comment]
Thanks for your work! I updated my new instance https://search.nya.pub

Everything works perfectly!

**Comment by Extravi** [comment]
> Thanks for your work! I updated my new instance https://search.nya.pub
> 
> Everything works perfectly!

I improved the image search and added torrent searching. If you want to update to that version or if you have any feedback on the user interface, etc., please let me know.

**Comment by Extravi** [comment]
https://github.com/Extravi/tailsx/commit/e7638511cb8a8c4a066868e6c3c0f8bf4f9fcffc

**Comment by Extravi** [comment]
made it faster

**Comment by Extravi** [comment]
etc

**Comment by Extravi** [comment]
i noticed you have a much faster image search how do you run gunicorn? or did you make any changes to the image search?

**Comment by vorons** [comment]
> i noticed you have a much faster image search how do you run gunicorn? or did you make any changes to the image search?

No, I didn't change anything. These are the default hosting settings. I don't even have access to the gunicorn settings, the hosting can only specify the executable script file.

**Comment by vorons** [comment]
> > Thanks for your work! I updated my new instance https://search.nya.pub
> > Everything works perfectly!
> 
> I improved the image search and added torrent searching. If you want to update to that version or if you have any feedback on the user interface, etc., please let me know.

Thank you! Updated too.

**Comment by Extravi** [comment]
np

> > > Thanks for your work! I updated my new instance https://search.nya.pub
> > > Everything works perfectly!
> > 
> > 
> > I improved the image search and added torrent searching. If you want to update to that version or if you have any feedback on the user interface, etc., please let me know.
> 
> Thank you! Updated too.

**Comment by Extravi** [comment]
> > i noticed you have a much faster image search how do you run gunicorn? or did you make any changes to the image search?
> 
> No, I didn't change anything. These are the default hosting settings. I don't even have access to the gunicorn settings, the hosting can only specify the executable script file.

oh so you dont know how its hosted by them?

**Comment by vorons** [comment]
> oh so you dont know how its hosted by them?

I only found this:

```
[uwsgi]
plugins-dir = /usr/data/uwsgi/%V/lib/
plugins = cheaper_busyness,router_static,python_3_11

http-socket = []:00
thunder lock

master
lazy-apps
need app
procname = uWSGI worker [794627]
procname-master = uWSGI master [794627]

offload-threads = 1
enable-threads=true
buffer-size = 32768
wsgi-disable-file-wrapper=true

# logs
logto=/home/user/admin/logs/uwsgi/794627.log
logto2=/home/user/admin/logs/uwsgi/794627.log
log-reopen = true
disable-logging

# Adaptive process spawning
cheaper = 1
cheaper-algo = busyness
cheaper initial = 1
cheaper-overload = 5
cheaper-busyness-min = 10
cheaper-busy-max = 90
processes = 20

#X-Sendfile
pull-header = X-Sendfile X_SENDFILE
response-route-if-not = empty:${X_SENDFILE} fastfile:filename=${X_SENDFILE}

# Set remote address
route-run = setremoteaddr:${HTTP_X_REAL_IP}

# application
chdir=/home/user/tailsx/tailsx/
wsgi = __init__
callable = app
pyhome=/home/user/tailsx/

# Static files
static safe = /home/user/
```
