### ISSUE TITLE
Container image

### ISSUE THREAD

**Issue by baduhai** [Extravi/tailsx#24]
Would be cool if there was a container image available, so this could be easily deployed with podman or docker :)

**Comment by baduhai** [comment]
It would also be nice if in said container image, you could set your domain as an env variable, and it automatically generated the opensearch.xml file.

**Comment by Extravi** [comment]
I don't know how to make a container image for docker sorry

**Comment by Extravi** [comment]
but you can host an instance using this https://github.com/Extravi/tailsx-docs

**Comment by Extravi** [comment]
@baduhai @TEMtheLEM https://github.com/Extravi/tailsx/pull/31 

docker support added
