### ISSUE TITLE
design feedback for image search

### ISSUE THREAD

**Issue by Extravi** [Extravi/tailsx#36]
![Screenshot_20230718_051933](https://github.com/Extravi/tailsx/assets/98912029/3a6e78f5-a059-4187-92fa-250fecd4b2c4)

**Comment by Extravi** [comment]
also if you have feedback for text search and any other thing please let me know

**Comment by Extravi** [comment]
![Screenshot_20230718_054251](https://github.com/Extravi/tailsx/assets/98912029/8b89afbd-72f6-4f04-8521-46825249c8aa)

**Comment by Extravi** [comment]
or i could do this above

**Comment by vorons** [comment]
> ![Screenshot_20230718_054251](https://user-images.githubusercontent.com/98912029/254221911-8b89afbd-72f6-4f04-8521-46825249c8aa.png)

Looks very cool! Are you planning to implement this?

**Comment by Extravi** [comment]
![Screenshot_20230718_061446](https://github.com/Extravi/tailsx/assets/98912029/ac98a61a-bf40-407b-990e-6794934a757e)

**Comment by Extravi** [comment]
moved everything over more

**Comment by Extravi** [comment]
> > ![Screenshot_20230718_054251](https://user-images.githubusercontent.com/98912029/254221911-8b89afbd-72f6-4f04-8521-46825249c8aa.png)
> 
> Looks very cool! Are you planning to implement this?

yes and i will add some other things with it soon

**Comment by Extravi** [comment]
> ![Screenshot_20230718_061446](https://user-images.githubusercontent.com/98912029/254231926-ac98a61a-bf40-407b-990e-6794934a757e.png)

this one is a bit better also if you have any ideas for what i could add to this project or improve on let me know thanks

**Comment by Extravi** [comment]
i did use javascript in https://github.com/Extravi/tailsx/commit/e7638511cb8a8c4a066868e6c3c0f8bf4f9fcffc to speed up results with a knowledge panel and i plan on doing more things with javascript

**Comment by amogusussy** [comment]
How can I see these changes? It isn't on the main instance, and there aren't any branches that have this change.

> @amogusussy do you have any feedback by any chance for the project?

The main issue I see right now with the project is that there's just one monolithic __init__.py script, which makes navigating the source harder, which makes people less likely to commit.
I think there should be one file to manage routes, one file for each of the different engines, and one for all the other pages e.g. settings, home page.
This just makes it a lot more organized, so it's easier to maintain.

**Comment by amogusussy** [comment]
On lite.qwant.com, you can get the title of each image by using the `alt` HTML tag on each of the images. I think it'd be good to use that as a title on this menu.

**Comment by Extravi** [comment]
> How can I see these changes? It isn't on the main instance, and there aren't any branches that have this change.
> 
> > @amogusussy do you have any feedback by any chance for the project?
> 
> The main issue I see right now with the project is that there's just one monolithic __init__.py script, which makes navigating the source harder, which makes people less likely to commit.
> I think there should be one file to manage routes, one file for each of the different engines, and one for all the other pages e.g. settings, home page.
> This just makes it a lot more organized, so it's easier to maintain.

isn't possible to see the changes for this at the moment because it's still in development

**Comment by Extravi** [comment]
> On lite.qwant.com, you can get the title of each image by using the `alt` HTML tag on each of the images. I think it'd be good to use that as a title on this menu.

![Screenshot_20230719_042225](https://github.com/Extravi/tailsx/assets/98912029/16b2eac9-97b0-47ed-a7bd-c81a4193a6d2)

**Comment by Extravi** [comment]
i have added that i also have some things i need to fix and improve before uploading it

**Comment by Extravi** [comment]
i was going to send a screen recording but flatpak obs wont work and i am not going to compile obs i am using gentoo linux atm

**Comment by Extravi** [comment]
![Screenshot_20230719_042858](https://github.com/Extravi/tailsx/assets/98912029/df4be04b-89fd-4034-a9a0-935c7a522fe6)

this is what i have atm for now

**Comment by Extravi** [comment]
i am quite new to javascript and i am still learning

**Comment by Extravi** [comment]
![Screenshot_20230719_044036](https://github.com/Extravi/tailsx/assets/98912029/ae561b13-d14d-4cbc-94fb-e14f8ce5d1e3)
![Screenshot_20230719_044053](https://github.com/Extravi/tailsx/assets/98912029/2fe7de50-f3b2-4601-bfcc-a11d7e243024)

**Comment by Extravi** [comment]
idk how to put the links back onto the side so it will be like this for now

**Comment by Extravi** [comment]
![Screenshot_20230719_044934](https://github.com/Extravi/tailsx/assets/98912029/740ccba1-1c8b-4517-8283-906892d74006)
![Screenshot_20230719_045014](https://github.com/Extravi/tailsx/assets/98912029/0d65babf-62fd-4302-924f-d7527ad26b58)

**Comment by Extravi** [comment]
Desktop:
![Screenshot_20230719_063030](https://github.com/Extravi/tailsx/assets/98912029/19e5a2f5-801d-41a9-bc00-c61780f22653)
Mobile:
![Screenshot_20230719_063106](https://github.com/Extravi/tailsx/assets/98912029/2c1735e8-5a7f-49da-ae7c-5b19ca880847)
I am going to upload the code soon and update my instance with it, but I will likely further improve it.

**Comment by Extravi** [comment]
https://github.com/Extravi/tailsx/commit/7264381a99faaad5ff6d8634945d470b4a4e132d

https://tailsx.extravi.dev/search?q=cyberpunk+tokyo&t=image

**Comment by Extravi** [comment]
let me know what you think or if  you have any feedback on it thanks
