### ISSUE TITLE
How to set default theme?

### ISSUE THREAD

**Issue by vorons** [Extravi/tailsx#37]
How to set default theme? I changed the dark style and want to make it the default.

![search](https://github.com/Extravi/tailsx/assets/3390639/5eac2b9f-f318-40ae-9120-e13116c8ad65)

![resault](https://github.com/Extravi/tailsx/assets/3390639/9fe9937b-affe-4db7-af09-2764144905ad)

**Comment by Extravi** [comment]
![Screenshot_20230718_061915](https://github.com/Extravi/tailsx/assets/98912029/70c58f71-dbcc-4c4d-ab7c-a9f1d288569f)
you can also move it to the top in settings if you want

**Comment by Extravi** [comment]
let me know if this worked thanks

**Comment by Extravi** [comment]
or if you have any questions

**Comment by vorons** [comment]
Oh thanks! I changed in _config.py file, it works. :+1:

**Comment by Extravi** [comment]
alright np
