### ISSUE TITLE
Interface feedback and ideas for a new private instances option in config.

### ISSUE THREAD

**Issue by Extravi** [Extravi/tailsx#51]
![image](https://github.com/Extravi/tailsx/assets/98912029/6a854ce7-9c2e-4634-9654-b9c1dd70829b)

**Comment by Extravi** [comment]
note: this is not done and it is still in development

**Comment by Extravi** [comment]
btw, this will work with APIs as you can set up a key in the config file for it.

**Comment by Extravi** [comment]
This should be useful for running TailsX on a local network using a Cloudflare tunnel.

**Comment by Extravi** [comment]
so you can protect your instance and host it at home

**Comment by Extravi** [comment]
this wont be used on any of my public instances i will keep thos open

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/tailsx/assets/98912029/521414c4-582b-432d-832a-903d27bd3754)

**Comment by amogusussy** [comment]
How is the username & password stored?
Also, I'd assume there'd only be one user, so is a username even necessary?

**Comment by Extravi** [comment]
> How is the username & password stored (are they encrypted, hashed, or stored in plain text)?
> Also, I'd assume there'd only be one user, so is a username even necessary?

needed something to save space so the username is only design

**Comment by Extravi** [comment]
> How is the username & password stored (are they encrypted, hashed, or stored in plain text)?
> Also, I'd assume there'd only be one user, so is a username even necessary?

the password would be set in the configuration file but it would never leave the server because the server will never send it back only a random session id

**Comment by Extravi** [comment]
> How is the username & password stored (are they encrypted, hashed, or stored in plain text)?
> Also, I'd assume there'd only be one user, so is a username even necessary?

not exactly sure how I would store a encrypted password atm

**Comment by amogusussy** [comment]
Could you make a new git branch so that people can review the changes before they're implemented? I could look at trying to implement some form of encryption before it's actually in the main release.

**Comment by Extravi** [comment]
yeah i could do that soon not atm as i need to clean it up

**Comment by amogusussy** [comment]
Okay👍

**Comment by Extravi** [comment]
I have school and other things to do, so this might take longer than other things I'm trying to add to TailsX. I will likely be able to add languages like French to the user interface before I finish with this.

**Comment by Extravi** [comment]
going to drop this for now to work on https://github.com/Extravi/tailsx/issues/52 and               ![Screenshot from 2023-10-06 23-20-08](https://github.com/Extravi/tailsx/assets/98912029/da8e9792-7bd3-44ab-b2f4-a6fffce360b7)

_Originally posted by @Extravi in https://github.com/Extravi/tailsx/issues/53#issuecomment-1751582157_
