### ISSUE TITLE
Torrent searches don´t work when searching quickly

### ISSUE THREAD

**Issue by MixoMax** [Extravi/tailsx#55]
Torrent searches sometimes return nothing found but when you reload the site 3-5 times it will eventually work. I presume this has something to do with rate limiting on the torrenting search engines end.

**Comment by Extravi** [comment]
it's an issue with the torrent site itself I am searching from it's slow

**Comment by Extravi** [comment]
also it probably is rate limiting

**Comment by MixoMax** [comment]
Maybe use another site like pirate bay?

**Comment by Extravi** [comment]
I am using the current site for the quality of the results

**Comment by Extravi** [comment]
I don't want to add any site to do with piracy into the code

**Comment by Extravi** [comment]
I will be adding support for other torrent sites tho
